-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 17:37:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotel_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_management` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hotel_management` ;

-- -----------------------------------------------------
-- Table `hotel_management`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management`.`customer` ;

CREATE TABLE IF NOT EXISTS `hotel_management`.`customer` (
  `Customer_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Last_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Phone_Number` VARCHAR(45) NULL DEFAULT NULL,
  `Email_Address` VARCHAR(45) NULL DEFAULT NULL,
  `Booking_Histroy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_management`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management`.`feedback` ;

CREATE TABLE IF NOT EXISTS `hotel_management`.`feedback` (
  `Feedback_ID` INT NOT NULL AUTO_INCREMENT,
  `Rating` DECIMAL(10,0) NULL DEFAULT NULL,
  `Comments` VARCHAR(45) NULL DEFAULT NULL,
  `Date_of_feedback` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Feedback_ID`),
  UNIQUE INDEX `Feedback_ID_UNIQUE` (`Feedback_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_management`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management`.`payment` ;

CREATE TABLE IF NOT EXISTS `hotel_management`.`payment` (
  `Payment_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cost_of_Room` DECIMAL(10,0) NULL DEFAULT NULL,
  `Service_used` VARCHAR(45) NULL DEFAULT NULL,
  `Taxes` DECIMAL(10,0) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Payment_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_management`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management`.`reservation` ;

CREATE TABLE IF NOT EXISTS `hotel_management`.`reservation` (
  `Reservation ID` INT UNSIGNED NOT NULL,
  `Arrival_and_departure_date` DATE NULL DEFAULT NULL,
  `Number_of_guest` VARCHAR(45) NULL DEFAULT NULL,
  `Special_prefernce` VARCHAR(45) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Reservation ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_management`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management`.`room` ;

CREATE TABLE IF NOT EXISTS `hotel_management`.`room` (
  `Room ID` INT UNSIGNED NOT NULL,
  `Type` VARCHAR(45) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `Price_Per_Night` DECIMAL(10,0) NULL DEFAULT NULL,
  `Special_Amenities` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Room ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_management`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management`.`services` ;

CREATE TABLE IF NOT EXISTS `hotel_management`.`services` (
  `Services_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Restaurant` VARCHAR(45) NULL DEFAULT NULL,
  `Gym` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `Opening_Hours` VARCHAR(45) NULL DEFAULT NULL,
  `Price` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`Services_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


INSERT INTO `hotel_management`.`customer` 
(First_Name, Last_Name, Phone_Number, Email_Address, Booking_Histroy)
VALUES 
('John', 'Doe', '123-456-7890', 'john.doe@example.com', 'Booking1'),
('Jane', 'Smith', '098-765-4321', 'jane.smith@example.com', 'Booking2');

INSERT INTO `hotel_management`.`feedback` 
(Rating, Comments, Date_of_feedback)
VALUES 
(5, 'Great service!', '2024-09-01'),
(3, 'Average experience.', '2024-09-05');

INSERT INTO `hotel_management`.`payment` 
(Cost_of_Room, Service_used, Taxes, Status)
VALUES 
(200, 'Room Service', 20, 'Paid'),
(150, 'Restaurant', 15, 'Unpaid');
 
INSERT INTO `hotel_management`.`reservation` 
(`Reservation ID`, Arrival_and_departure_date, Number_of_guest, Special_prefernce, Status)
VALUES 
(1, '2024-09-10', '2', 'Near window', 'Confirmed'),
(2, '2024-09-12', '1', 'Quiet room', 'Pending');

INSERT INTO `hotel_management`.`room` 
(`Room ID`, Type, Status, Price_Per_Night, Special_Amenities)
VALUES 
(1, 'Single', 'Available', 100, 'Free Wi-Fi'),
(2, 'Double', 'Occupied', 150, 'Ocean view');

INSERT INTO `hotel_management`.`services` 
(Restaurant, Gym, Description, Opening_Hours, Price)
VALUES 
('Open', 'Yes', 'Full-service restaurant', '6 AM - 10 PM', 50),
('Closed', 'No', '24/7 gym access', 'Always open', 30);




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
